name: lobehub
services:
  network-service:
    image: 192.168.1.211:5001/naiyun-registry/alpine:latest
    container_name: NaiYun-network
    restart: always
    ports:
      - '${LOBE_PORT:-3010}:3210' # LobeChat Web
    command: tail -f /dev/null
    networks:
      - lobe-network

  lobe:
    image: naiyunchat-db:${NAIYUNCHAT_DB_VERSION:-2.2.4}
    pull_policy: never
    container_name: NaiYunHub
    restart: always
    network_mode: 'service:network-service'
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
      searxng:
        condition: service_started
    env_file:
      - ${NAIYUN_ENV_FILE:-../../.env.development}
    environment:
      - 'APP_URL=${APP_URL:-http://127.0.0.1:3010}'
      - 'INTERNAL_APP_URL=http://127.0.0.1:3210'
      - 'DATABASE_DRIVER=node'
      - 'DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@127.0.0.1:5432/${LOBE_DB_NAME:-postgres}'
      - 'REDIS_URL=redis://127.0.0.1:6379'
      - 'REDIS_PREFIX=${REDIS_PREFIX:-lobechat}'
      - 'REDIS_TLS=0'
      - 'SEARXNG_URL=http://127.0.0.1:8080'

  postgresql:
    image: 192.168.1.211:5001/naiyun-registry/paradedb/paradedb:latest-pg17
    container_name: NaiYun-postgres
    restart: always
    network_mode: 'service:network-service'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME:-postgres}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: 192.168.1.211:5001/naiyun-registry/redis:7-alpine
    container_name: NaiYun-redis
    restart: always
    network_mode: 'service:network-service'
    command: redis-server --save 60 1000 --appendonly yes
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  searxng:
    image: 192.168.1.211:5001/naiyun-registry/searxng/searxng:latest
    container_name: NaiYun-searxng
    restart: always
    network_mode: 'service:network-service'
    volumes:
      - './searxng-settings.yml:/etc/searxng/settings.yml'
    environment:
      - 'SEARXNG_SETTINGS_FILE=/etc/searxng/settings.yml'

volumes:
  redis_data:
    driver: local

networks:
  lobe-network:
    driver: bridge
